In [93]:
import numpy as np
import pandas as pd

In [94]:
df = pd.read_csv("Movie_classification.csv")

In [95]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [97]:
df["Time_taken"].fillna(value=df["Time_taken"].mean(),inplace=True)

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [99]:
df = pd.get_dummies(df,columns=["3D_available","Genre"],drop_first=True)

In [100]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags  \
0            7.995           7.94  ...      109.60          223.840   
1            7.470           7.44  ...      146.64          243.456   
2            7.515           7.44  ...      147.88         2022.400   
3            7.020           8.26  ...      185.36          225.344   
4            7.070           8.26  ...      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  Start_Tech_Oscar  \
0              23            494       48000                 1   
1              42            462       43200                 0   
2              38            458       69400                 1   
3              45            472       66800                 1   
4              55            395       72400                 1   

   3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0                 1             0            0               1  
1                 0             0            1               0  
2                 0             1            0               0  
3                 1             0            1               0  
4                 0             0            1               0  

[5 rows x 21 columns]

In [101]:
X = df.loc[:,df.columns!="Start_Tech_Oscar"]
type(X)

pandas.core.frame.DataFrame

In [102]:
y = df["Start_Tech_Oscar"]
type(y)

pandas.core.series.Series

In [103]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Start_Tech_Oscar, dtype: int64

In [104]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [105]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(404, 20) (102, 20) (404,) (102,)


In [106]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler().fit(X_train)

In [107]:
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [108]:
X_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

# training SVM

In [109]:
from sklearn import svm

In [110]:
clf_svm_1 = svm.SVC(kernel='linear',C=0.01)
clf_svm_1.fit(X_train_std,y_train)

SVC(C=0.01, kernel='linear')

# predict values using trained mode

In [111]:
y_test_pred = clf_svm_1.predict(X_test_std)

In [112]:
y_test_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0])

# Model performance

In [113]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [114]:
confusion_matrix(y_test,y_test_pred)

array([[11, 33],
       [ 5, 53]])

In [115]:
accuracy_score(y_test,y_test_pred)

0.6274509803921569

In [116]:
clf_svm_1.n_support_

array([186, 189], dtype=int32)

# Grid search 

In [117]:
from sklearn.model_selection import GridSearchCV
params = {"C":[0.001,0.005,0.01,0.05,0.1,0.5,1,5,10,100,500,1000],"kernel":("rbf","poly")}

In [118]:
svm_grid_lin = GridSearchCV(clf_svm_1,params,n_jobs=-1,cv=10,verbose=10,scoring="accuracy")

In [119]:
svm_grid_lin.fit(X_train_std,y_train)

Fitting 10 folds for each of 24 candidates, totalling 240 fits


GridSearchCV(cv=10, estimator=SVC(C=0.01, kernel='linear'), n_jobs=-1,
             param_grid={'C': [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10,
                               100, 500, 1000],
                         'kernel': ('rbf', 'poly')},
             scoring='accuracy', verbose=10)

In [120]:
svm_grid_lin.best_params_

{'C': 5, 'kernel': 'rbf'}

In [121]:
linsvm_clf = svm_grid_lin.best_estimator_

In [122]:
accuracy_score(y_test,linsvm_clf.predict(X_test_std))

0.6176470588235294

# Polynomial

In [123]:
clf_svm_p3 = svm.SVC(kernel='poly',degree=3,C=0.5)
clf_svm_p3.fit(X_train_std,y_train)

SVC(C=0.5, kernel='poly')

In [124]:
accuracy_score(y_test,clf_svm_p3.predict(X_test_std))

0.5686274509803921

In [125]:
clf_svm_p3.n_support_

array([177, 189], dtype=int32)

# Radial

In [127]:
clf_svm_rad = svm.SVC(kernel="rbf",C=0.6,gamma=0.5)
clf_svm_rad.fit(X_train_std,y_train)

SVC(C=0.6, gamma=0.5)

In [128]:
accuracy_score(y_test,clf_svm_rad.predict(X_test_std))

0.5588235294117647

# Radial Grid

In [135]:
params = {"C":[0.01,0.05,0.1,0.5,1,5,10,50,100,250,500,100],"gamma":(0.001,0.01,0.1,1,0.5)}

In [136]:
clf_svm_r = svm.SVC(kernel="rbf")

In [137]:
grid_clf_r = GridSearchCV(clf_svm_r,params,n_jobs=-1,verbose=1,cv=10,scoring="accuracy")

In [138]:
grid_clf_r.fit(X_train_std,y_train)

Fitting 10 folds for each of 60 candidates, totalling 600 fits


GridSearchCV(cv=10, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100, 250,
                               500, 100],
                         'gamma': (0.001, 0.01, 0.1, 1, 0.5)},
             scoring='accuracy', verbose=1)

In [139]:
grid_clf_r.best_params_

{'C': 100, 'gamma': 0.001}

In [140]:
cvgrid_clf_r = grid_clf_r.best_estimator_

In [141]:
accuracy_score(y_test,cvgrid_clf_r.predict(X_test_std))

0.5980392156862745

In [142]:
cvgrid_clf_r.n_support_

array([155, 164], dtype=int32)